// lang.js

const LANG_EN = {
    GREETING: "Gurasuraisu loaded successfully",
    LICENCE: "Gurasuraisu is made by kirbIndustries, and is licensed under the GNU General Public License, Version 2.0 (GPL-2.0)",
    WELCOME_MESSAGE: "Hello, welcome to Gurasuraisu!",
    PLACEHOLDER_MESSAGE: "Type your message",
    SEND: "Send",
    VOICE: "Voice",
    SEARCH_PLACEHOLDER: "Search",
    CONTROLS: "Controls",
    SILENT: "Silent",
    TONE: "Tone",
    MINIMAL: "Minimal",
    DAYLIGHT: "Daylight",
    WEATHER: "Weather",
    GURAPPS: "Gurapps",
    SECONDS: "Seconds",
    MOTION: "Motion",
    CONTRAST: "Contrast",
    WALLPAPER: "Wallpaper",
    ADD: "Add",
    STYLE: "Style",
    ADJUST: "Adjust",
    LANGPICK: "Language",
    INSTALL_PROMPT: "Install as an app to get all features",
    OFFLINE: "You are offline",
    ONLINE: "You are online",
    FAIL_WEATHER: "Failed to retrieve weather",
    FULLSCREEN: "Fullscreen",
    SETUP_COMPLETE: "Setup complete",
    OPEN_SETTINGS: "Opening Settings",
    OPEN_WEATHER: "Opening Weather",
    APP_OPENED: "{app} app opened",
    APP_OPEN_FAIL: "Failed to open {app}",
    WALLPAPER_UPDATED: "Wallpaper updated",
    WALLPAPER_UPDATE_FAIL: "Failed to update wallpaper",
    MULTIPLE_WALLPAPERS_UPDATED: "Multiple wallpapers updated",
    NO_VALID_WALLPAPERS: "No valid wallpapers found",
    WALLPAPER_CHANGE: "Wallpaper changed",
    SLIDESHOW_WALLPAPER: "Slideshow wallpaper",
    WALLPAPER_SAVE_FAIL: "Failed to save wallpaper",
    WALLPAPER_HISTORY_FAIL: "Failed to save wallpaper history",
    LOAD_SUCCESS: "Gurasuraisu loaded successfully",
    NOT_FULLSCREEN: "Not fullscreen",
    CHECK_WORDS: ['updated', 'complete', 'done', 'success', 'completed', 'ready', 'successfully', 'accepted', 'accept', 'yes'],
    CLOSE_WORDS: ['failed', 'canceled', 'error', 'failure', 'fail', 'cancel', 'rejected', 'reject', 'not', 'no']
};

const LANG_JP = {
    GREETING: "ぐらするらいす読み込み成功",
    LICENCE: "ぐらするらいすはkirbIndustriesによって作られ、GNU General Public License, Version 2.0 (GPL-2.0)の下でライセンスされています。",
    WELCOME_MESSAGE: "こんにちは、ぐらすりすへようこそ！",
    PLACEHOLDER_MESSAGE: "メッセージを入力してください",
    SEND: "送信",
    VOICE: "音声",
    SEARCH_PLACEHOLDER: "検索",
    CONTROLS: "コントロール",
    SILENT: "サイレント",
    TONE: "トーン",
    MINIMAL: "最小",
    DAYLIGHT: "昼光",
    WEATHER: "天気",
    GURAPPS: "グラップス",
    SECONDS: "セコンド",
    MOTION: "モーション",
    CONTRAST: "コントラスト",
    WALLPAPER: "壁紙",
    ADD: "追加",
    STYLE: "スタイル",
    ADJUST: "調整",
    LANGPICK: "言語",
    INSTALL_PROMPT: "アプリとしてインストールしてすべての機能を利用",
    OFFLINE: "オフラインです",
    ONLINE: "オンラインです",
    FAIL_WEATHER: "天気を取得できませんでした",
    FULLSCREEN: "全画面",
    SETUP_COMPLETE: "セットアップ完了",
    OPEN_SETTINGS: "設定を開いています",
    OPEN_WEATHER: "天気を開いています",
    APP_OPENED: "{app} アプリを開きました",
    APP_OPEN_FAIL: "{app} を開けませんでした",
    WALLPAPER_UPDATED: "壁紙が更新されました",
    WALLPAPER_UPDATE_FAIL: "壁紙の更新に失敗しました",
    MULTIPLE_WALLPAPERS_UPDATED: "複数の壁紙が更新されました",
    NO_VALID_WALLPAPERS: "有効な壁紙が見つかりませんでした",
    WALLPAPER_CHANGE: "壁紙が変更されました",
    SLIDESHOW_WALLPAPER: "スライドショーの壁紙",
    WALLPAPER_SAVE_FAIL: "壁紙の保存に失敗しました",
    WALLPAPER_HISTORY_FAIL: "壁紙履歴の保存に失敗しました",
    LOAD_SUCCESS: "ぐらするらいす読み込み成功",
    NOT_FULLSCREEN: "全画面ではありません",
    CHECK_WORDS: ['更新', '完了', '成功', '準備完了', '受け入れ', 'はい'],
    CLOSE_WORDS: ['失敗', 'キャンセル', 'エラー', '故障', '拒否', '違う', 'いいえ']
};
