// lang.js

const LANG_EN = {
    GREETING: "Gurasuraisu loaded successfully",
    LICENCE: "Gurasuraisu is made by kirbIndustries, and is licensed under the GNU General Public License, Version 2.0 (GPL-2.0)",
    WELCOME_MESSAGE: "Hello, welcome to Gurasuraisu!",
    PLACEHOLDER_MESSAGE: "Type your message",
    SEND: "Send",
    VOICE: "Voice",
    SEARCH_PLACEHOLDER: "Search",
    CONTROLS: "Controls",
    SILENT: "Silent",
    TONE: "Tone",
    MINIMAL: "Minimal",
    DAYLIGHT: "Daylight",
    WEATHER: "Weather",
    GURAPPS: "Gurapps",
    SECONDS: "Seconds",
    MOTION: "Motion",
    CONTRAST: "Contrast",
    WALLPAPER: "Wallpaper",
    ADD: "Add",
    STYLE: "Style",
    ADJUST: "Adjust",
    LANGPICK: "Language",
    INSTALL_PROMPT: "Install as an app to get all features",
    OFFLINE: "You are offline",
    ONLINE: "You are online",
    FAIL_WEATHER: "Failed to retrieve weather",
    FULLSCREEN: "Fullscreen",
    SETUP_COMPLETE: "Setup complete",
    OPEN_SETTINGS: "Opening Settings",
    OPEN_WEATHER: "Opening Weather",
    APP_OPENED: "{app} app opened",
    APP_OPEN_FAIL: "Failed to open {app}",
    WALLPAPER_UPDATED: "Wallpaper updated",
    WALLPAPER_UPDATE_FAIL: "Failed to update wallpaper",
    MULTIPLE_WALLPAPERS_UPDATED: "Multiple wallpapers updated",
    NO_VALID_WALLPAPERS: "No valid wallpapers found",
    WALLPAPER_CHANGE: "Wallpaper changed",
    SLIDESHOW_WALLPAPER: "Slideshow wallpaper",
    WALLPAPER_SAVE_FAIL: "Failed to save wallpaper",
    WALLPAPER_HISTORY_FAIL: "Failed to save wallpaper history",
    LOAD_SUCCESS: "Gurasuraisu loaded successfully",
    NOT_FULLSCREEN: "Not fullscreen",
    CLOCK_STYLE_FAILED: "Failed to load Clock Style",
    CHECK_WORDS: ['updated', 'complete', 'done', 'success', 'completed', 'ready', 'successfully', 'accepted', 'accept', 'yes'],
    CLOSE_WORDS: ['failed', 'canceled', 'error', 'failure', 'fail', 'cancel', 'rejected', 'reject', 'not', 'no'],
    DEFAULT: "Default",
    WORK: "Work",
    PUFFY: "Puffy",
    CLASSIC: "Classic",
    STROKES: "Strokes",
    MONO: "Mono",
    PIXEL: "Pixel",
    WRITTEN: "Written",
    RAISED: "Raised",
    DOT: "Dot",
    ROUND: "Round"
};

const LANG_JP = {
    GREETING: "ぐらするらいす読み込み成功",
    LICENCE: "ぐらするらいすはkirbIndustriesによって作られ、GNU General Public License, Version 2.0 (GPL-2.0)の下でライセンスされています。",
    WELCOME_MESSAGE: "こんにちは、ぐらすりすへようこそ！",
    PLACEHOLDER_MESSAGE: "メッセージを入力してください",
    SEND: "送信",
    VOICE: "音声",
    SEARCH_PLACEHOLDER: "検索",
    CONTROLS: "コントロール",
    SILENT: "サイレント",
    TONE: "トーン",
    MINIMAL: "最小",
    DAYLIGHT: "昼光",
    WEATHER: "天気",
    GURAPPS: "グーラのアプリ",
    SECONDS: "セコンド",
    MOTION: "モーション",
    CONTRAST: "コントラスト",
    WALLPAPER: "壁紙",
    ADD: "追加",
    STYLE: "スタイル",
    ADJUST: "調整",
    LANGPICK: "言語",
    INSTALL_PROMPT: "アプリとしてインストールしてすべての機能を利用",
    OFFLINE: "オフラインです",
    ONLINE: "オンラインです",
    FAIL_WEATHER: "天気を取得できませんでした",
    FULLSCREEN: "全画面",
    SETUP_COMPLETE: "セットアップ完了",
    OPEN_SETTINGS: "設定を開いています",
    OPEN_WEATHER: "天気を開いています",
    APP_OPENED: "{app} アプリを開きました",
    APP_OPEN_FAIL: "{app} を開けませんでした",
    WALLPAPER_UPDATED: "壁紙が更新されました",
    WALLPAPER_UPDATE_FAIL: "壁紙の更新に失敗しました",
    MULTIPLE_WALLPAPERS_UPDATED: "複数の壁紙が更新されました",
    NO_VALID_WALLPAPERS: "有効な壁紙が見つかりませんでした",
    WALLPAPER_CHANGE: "壁紙が変更されました",
    SLIDESHOW_WALLPAPER: "スライドショーの壁紙",
    WALLPAPER_SAVE_FAIL: "壁紙の保存に失敗しました",
    WALLPAPER_HISTORY_FAIL: "壁紙履歴の保存に失敗しました",
    LOAD_SUCCESS: "ぐらするらいす読み込み成功",
    NOT_FULLSCREEN: "全画面ではありません",
    CLOCK_STYLE_FAILED: "クロックスタイルのロードに失敗しました",
    CHECK_WORDS: ['更新', '完了', '成功', '準備完了', '受け入れ', 'はい'],
    CLOSE_WORDS: ['失敗', 'キャンセル', 'エラー', '故障', '拒否', '違う', 'いいえ'],
    DEFAULT: "デフォルト",
    WORK: "仕事",
    PUFFY: "ふっくら",
    CLASSIC: "クラシック",
    STROKES: "ストローク",
    MONO: "モノ",
    PIXEL: "ピクセル",
    WRITTEN: "手書き",
    RAISED: "隆起",
    DOT: "ドット",
    ROUND: "丸い"
};

const LANG_DE = {
    GREETING: "Gurasuraisu erfolgreich geladen",
    LICENCE: "Gurasuraisu wird von kirbIndustries erstellt und ist unter der GNU General Public License, Version 2.0 (GPL-2.0) lizenziert.",
    WELCOME_MESSAGE: "Hallo, willkommen bei Gurasuraisu!",
    PLACEHOLDER_MESSAGE: "Geben Sie Ihre Nachricht ein",
    SEND: "Senden",
    VOICE: "Sprache",
    SEARCH_PLACEHOLDER: "Suchen",
    CONTROLS: "Steuerelemente",
    SILENT: "Stumm",
    TONE: "Ton",
    MINIMAL: "Minimal",
    DAYLIGHT: "Tageslicht",
    WEATHER: "Wetter",
    GURAPPS: "Gura-Anwendungen",
    SECONDS: "Sekunden",
    MOTION: "Bewegung",
    CONTRAST: "Kontrast",
    WALLPAPER: "Hintergrundbild",
    ADD: "Hinzufügen",
    STYLE: "Stil",
    ADJUST: "Anpassen",
    LANGPICK: "Sprache",
    INSTALL_PROMPT: "Als App installieren, um alle Funktionen zu erhalten",
    OFFLINE: "Sie sind offline",
    ONLINE: "Sie sind online",
    FAIL_WEATHER: "Wetter konnte nicht abgerufen werden",
    FULLSCREEN: "Vollbild",
    SETUP_COMPLETE: "Einrichtung abgeschlossen",
    OPEN_SETTINGS: "Einstellungen öffnen",
    OPEN_WEATHER: "Wetter öffnen",
    APP_OPENED: "App {app} geöffnet",
    APP_OPEN_FAIL: "App {app} konnte nicht geöffnet werden",
    WALLPAPER_UPDATED: "Hintergrundbild aktualisiert",
    WALLPAPER_UPDATE_FAIL: "Hintergrundbild konnte nicht aktualisiert werden",
    MULTIPLE_WALLPAPERS_UPDATED: "Mehrere Hintergrundbilder aktualisiert",
    NO_VALID_WALLPAPERS: "Keine gültigen Hintergrundbilder gefunden",
    WALLPAPER_CHANGE: "Hintergrundbild geändert",
    SLIDESHOW_WALLPAPER: "Diashow-Hintergrundbild",
    WALLPAPER_SAVE_FAIL: "Hintergrundbild konnte nicht gespeichert werden",
    WALLPAPER_HISTORY_FAIL: "Hintergrundbildverlauf konnte nicht gespeichert werden",
    LOAD_SUCCESS: "Gurasuraisu erfolgreich geladen",
    NOT_FULLSCREEN: "Nicht im Vollbildmodus",
    CLOCK_STYLE_FAILED: "Uhrstil konnte nicht geladen werden",
    CHECK_WORDS: ['aktualisiert', 'abgeschlossen', 'fertig', 'erfolg', 'erfolgreich', 'akzeptiert', 'akzeptieren', 'ja'],
    CLOSE_WORDS: ['fehlgeschlagen', 'abgebrochen', 'fehler', 'fehler', 'abbrechen', 'abgelehnt', 'ablehnen', 'nein'],
    DEFAULT: "Standard",
    WORK: "Arbeit",
    PUFFY: "Puffy",
    CLASSIC: "Klassisch",
    STROKES: "Striche",
    MONO: "Mono",
    PIXEL: "Pixel",
    WRITTEN: "Geschrieben",
    RAISED: "Erhoben",
    DOT: "Punkt",
    ROUND: "Rund"
};

const LANG_FR = {
    GREETING: "Gurasuraisu chargé avec succès",
    LICENCE: "Gurasuraisu est créé par kirbIndustries, et est sous licence GNU General Public License, Version 2.0 (GPL-2.0)",
    WELCOME_MESSAGE: "Bonjour, bienvenue sur Gurasuraisu !",
    PLACEHOLDER_MESSAGE: "Tapez votre message",
    SEND: "Envoyer",
    VOICE: "Voix",
    SEARCH_PLACEHOLDER: "Rechercher",
    CONTROLS: "Contrôles",
    SILENT: "Silencieux",
    TONE: "Tonalité",
    MINIMAL: "Minimal",
    DAYLIGHT: "Lumière",
    WEATHER: "Météo",
    GURAPPS: "Applications Gura",
    SECONDS: "Secondes",
    MOTION: "Mouvement",
    CONTRAST: "Contraste",
    WALLPAPER: "Fond d'écran",
    ADD: "Ajouter",
    STYLE: "Style",
    ADJUST: "Ajuster",
    LANGPICK: "Langue",
    INSTALL_PROMPT: "Installez en tant qu'application pour obtenir toutes les fonctionnalités",
    OFFLINE: "Vous êtes hors ligne",
    ONLINE: "Vous êtes en ligne",
    FAIL_WEATHER: "Impossible de récupérer la météo",
    FULLSCREEN: "Plein écran",
    SETUP_COMPLETE: "Configuration terminée",
    OPEN_SETTINGS: "Ouverture des paramètres",
    OPEN_WEATHER: "Ouverture de la météo",
    APP_OPENED: "L'application {app} est ouverte",
    APP_OPEN_FAIL: "Impossible d'ouvrir {app}",
    WALLPAPER_UPDATED: "Fond d'écran mis à jour",
    WALLPAPER_UPDATE_FAIL: "Impossible de mettre à jour le fond d'écran",
    MULTIPLE_WALLPAPERS_UPDATED: "Plusieurs fonds d'écran mis à jour",
    NO_VALID_WALLPAPERS: "Aucun fond d'écran valide trouvé",
    WALLPAPER_CHANGE: "Fond d'écran changé",
    SLIDESHOW_WALLPAPER: "Fond d'écran en diaporama",
    WALLPAPER_SAVE_FAIL: "Impossible de sauvegarder le fond d'écran",
    WALLPAPER_HISTORY_FAIL: "Impossible de sauvegarder l'historique des fonds d'écran",
    LOAD_SUCCESS: "Gurasuraisu chargé avec succès",
    NOT_FULLSCREEN: "Pas en plein écran",
    CLOCK_STYLE_FAILED: "Impossible de charger le style d'horloge",
    CHECK_WORDS: ['mis à jour', 'terminé', 'fait', 'succès', 'complété', 'prêt', 'avec succès', 'accepté', 'accepter', 'oui'],
    CLOSE_WORDS: ['échoué', 'annulé', 'erreur', 'échec', 'rater', 'annuler', 'rejeté', 'rejeter', 'pas', 'non'],
    DEFAULT: "Par défaut",
    WORK: "Travail",
    PUFFY: "Gonflé",
    CLASSIC: "Classique",
    STROKES: "Traits",
    MONO: "Mono",
    PIXEL: "Pixel",
    WRITTEN: "Écrit",
    RAISED: "En relief",
    DOT: "Point",
    ROUND: "Rond"
};

const LANG_ES = {
    GREETING: "Gurasuraisu cargado con éxito",
    LICENCE: "Gurasuraisu es creado por kirbIndustries y está licenciado bajo la Licencia Pública General de GNU, Versión 2.0 (GPL-2.0).",
    WELCOME_MESSAGE: "¡Hola, bienvenido a Gurasuraisu!",
    PLACEHOLDER_MESSAGE: "Escriba su mensaje",
    SEND: "Enviar",
    VOICE: "Voz",
    SEARCH_PLACEHOLDER: "Buscar",
    CONTROLS: "Controles",
    SILENT: "Silencio",
    TONE: "Tono",
    MINIMAL: "Mínimo",
    DAYLIGHT: "Luz del día",
    WEATHER: "Clima",
    GURAPPS: "Aplicaciones Gura",
    SECONDS: "Segundos",
    MOTION: "Movimiento",
    CONTRAST: "Contraste",
    WALLPAPER: "Fondo de pantalla",
    ADD: "Añadir",
    STYLE: "Estilo",
    ADJUST: "Ajustar",
    LANGPICK: "Idioma",
    INSTALL_PROMPT: "Instale como una aplicación para obtener todas las funciones",
    OFFLINE: "Estás desconectado",
    ONLINE: "Estás conectado",
    FAIL_WEATHER: "No se pudo recuperar el clima",
    FULLSCREEN: "Pantalla completa",
    SETUP_COMPLETE: "Configuración completa",
    OPEN_SETTINGS: "Abrir ajustes",
    OPEN_WEATHER: "Abrir clima",
    APP_OPENED: "Aplicación {app} abierta",
    APP_OPEN_FAIL: "No se pudo abrir {app}",
    WALLPAPER_UPDATED: "Fondo de pantalla actualizado",
    WALLPAPER_UPDATE_FAIL: "No se pudo actualizar el fondo de pantalla",
    MULTIPLE_WALLPAPERS_UPDATED: "Múltiples fondos de pantalla actualizados",
    NO_VALID_WALLPAPERS: "No se encontraron fondos de pantalla válidos",
    WALLPAPER_CHANGE: "Fondo de pantalla cambiado",
    SLIDESHOW_WALLPAPER: "Fondo de pantalla de presentación de diapositivas",
    WALLPAPER_SAVE_FAIL: "No se pudo guardar el fondo de pantalla",
    WALLPAPER_HISTORY_FAIL: "No se pudo guardar el historial del fondo de pantalla",
    LOAD_SUCCESS: "Gurasuraisu cargado con éxito",
    NOT_FULLSCREEN: "No está en pantalla completa",
    CLOCK_STYLE_FAILED: "No se pudo cargar el estilo del reloj",
    CHECK_WORDS: ['actualizado', 'completo', 'listo', 'éxito', 'exitosamente', 'aceptado', 'aceptar', 'sí'],
    CLOSE_WORDS: ['fallido', 'cancelado', 'error', 'fracaso', 'cancelar', 'rechazado', 'rechazar', 'no'],
    DEFAULT: "Predeterminado",
    WORK: "Trabajo",
    PUFFY: "Esponjoso",
    CLASSIC: "Clásico",
    STROKES: "Trazos",
    MONO: "Mono",
    PIXEL: "Píxel",
    WRITTEN: "Escrito",
    RAISED: "Elevado",
    DOT: "Punto",
    ROUND: "Redondo"
};

const LANG_KO = {
    GREETING: "Gurasuraisu가 성공적으로 로드되었습니다",
    LICENCE: "Gurasuraisu는 kirbIndustries에서 제작되었으며 GNU General Public License, Version 2.0 (GPL-2.0)에 따라 라이선스가 부여됩니다.",
    WELCOME_MESSAGE: "안녕하세요, Gurasuraisu에 오신 것을 환영합니다!",
    PLACEHOLDER_MESSAGE: "메시지를 입력하세요",
    SEND: "보내기",
    VOICE: "음성",
    SEARCH_PLACEHOLDER: "검색",
    CONTROLS: "컨트롤",
    SILENT: "무음",
    TONE: "톤",
    MINIMAL: "최소",
    DAYLIGHT: "주광",
    WEATHER: "날씨",
    GURAPPS: "구라앱",
    SECONDS: "초",
    MOTION: "모션",
    CONTRAST: "대비",
    WALLPAPER: "배경 화면",
    ADD: "추가",
    STYLE: "스타일",
    ADJUST: "조정",
    LANGPICK: "언어",
    INSTALL_PROMPT: "모든 기능을 사용하려면 앱으로 설치하세요",
    OFFLINE: "오프라인 상태입니다",
    ONLINE: "온라인 상태입니다",
    FAIL_WEATHER: "날씨를 가져오지 못했습니다",
    FULLSCREEN: "전체 화면",
    SETUP_COMPLETE: "설정 완료",
    OPEN_SETTINGS: "설정 열기",
    OPEN_WEATHER: "날씨 열기",
    APP_OPENED: "{app} 앱이 열렸습니다",
    APP_OPEN_FAIL: "{app} 앱을 열 수 없습니다",
    WALLPAPER_UPDATED: "배경 화면이 업데이트되었습니다",
    WALLPAPER_UPDATE_FAIL: "배경 화면 업데이트에 실패했습니다",
    MULTIPLE_WALLPAPERS_UPDATED: "여러 배경 화면이 업데이트되었습니다",
    NO_VALID_WALLPAPERS: "유효한 배경 화면을 찾을 수 없습니다",
    WALLPAPER_CHANGE: "배경 화면이 변경되었습니다",
    SLIDESHOW_WALLPAPER: "슬라이드 쇼 배경 화면",
    WALLPAPER_SAVE_FAIL: "배경 화면 저장에 실패했습니다",
    WALLPAPER_HISTORY_FAIL: "배경 화면 기록 저장에 실패했습니다",
    LOAD_SUCCESS: "Gurasuraisu가 성공적으로 로드되었습니다",
    NOT_FULLSCREEN: "전체 화면이 아닙니다",
    CLOCK_STYLE_FAILED: "시계 스타일 로드에 실패했습니다",
    CHECK_WORDS: ['업데이트됨', '완료됨', '완료', '성공', '성공적으로', '수락됨', '수락', '예'],
    CLOSE_WORDS: ['실패', '취소됨', '오류', '실패', '취소', '거부됨', '거부', '아니요'],
    DEFAULT: "기본",
    WORK: "작업",
    PUFFY: "푹신한",
    CLASSIC: "클래식",
    STROKES: "획",
    MONO: "모노",
    PIXEL: "픽셀",
    WRITTEN: "필기체",
    RAISED: "돌출된",
    DOT: "점",
    ROUND: "둥근"
};

const LANG_ZH = {
    GREETING: "Gurasuraisu加载成功",
    LICENCE: "Gurasuraisu由kirbIndustries制作，并根据GNU通用公共许可证，版本2.0（GPL-2.0）获得许可",
    WELCOME_MESSAGE: "你好，欢迎来到Gurasuraisu！",
    PLACEHOLDER_MESSAGE: "输入您的消息",
    SEND: "发送",
    VOICE: "语音",
    SEARCH_PLACEHOLDER: "搜索",
    CONTROLS: "控制",
    SILENT: "静音",
    TONE: "音调",
    MINIMAL: "最小",
    DAYLIGHT: "日光",
    WEATHER: "天气",
    GURAPPS: "古拉应用程序",
    SECONDS: "秒",
    MOTION: "运动",
    CONTRAST: "对比度",
    WALLPAPER: "壁纸",
    ADD: "添加",
    STYLE: "样式",
    ADJUST: "调整",
    LANGPICK: "语言",
    INSTALL_PROMPT: "安装为应用程序以获取所有功能",
    OFFLINE: "您已离线",
    ONLINE: "您已在线",
    FAIL_WEATHER: "无法检索天气",
    FULLSCREEN: "全屏",
    SETUP_COMPLETE: "设置完成",
    OPEN_SETTINGS: "打开设置",
    OPEN_WEATHER: "打开天气",
    APP_OPENED: "{app}应用程序已打开",
    APP_OPEN_FAIL: "无法打开{app}",
    WALLPAPER_UPDATED: "壁纸已更新",
    WALLPAPER_UPDATE_FAIL: "无法更新壁纸",
    MULTIPLE_WALLPAPERS_UPDATED: "多个壁纸已更新",
    NO_VALID_WALLPAPERS: "找不到有效的壁纸",
    WALLPAPER_CHANGE: "壁纸已更改",
    SLIDESHOW_WALLPAPER: "幻灯片壁纸",
    WALLPAPER_SAVE_FAIL: "无法保存壁纸",
    WALLPAPER_HISTORY_FAIL: "无法保存壁纸历史记录",
    LOAD_SUCCESS: "Gurasuraisu加载成功",
    NOT_FULLSCREEN: "不是全屏",
    CLOCK_STYLE_FAILED: "无法加载时钟样式",
    CHECK_WORDS: ['已更新', '完成', '完成', '成功', '成功地', '已接受', '接受', '是'],
    CLOSE_WORDS: ['失败', '已取消', '错误', '失败', '取消', '已拒绝', '拒绝', '不'],
    DEFAULT: "默认",
    WORK: "工作",
    PUFFY: "蓬松",
    CLASSIC: "经典",
    STROKES: "笔画",
    MONO: "单色",
    PIXEL: "像素",
    WRITTEN: "手写",
    RAISED: "凸起",
    DOT: "点",
    ROUND: "圆形"
};
