const LANG_EN = {
    GREETING: "Gurasuraisu loaded successfully",
    LICENCE: "Gurasuraisu is made by kirbIndustries, and is licensed under the GNU General Public License, Version 2.0 (GPL-2.0)",
    WELCOME_MESSAGE: "Hello, welcome to Gurasuraisu!",
    PLACEHOLDER_MESSAGE: "Type your message",
    SEND: "Send",
    VOICE: "Voice",
    SEARCH_PLACEHOLDER: "Search",
    CONTROLS: "Controls",
    SILENT: "Silent",
    TONE: "Tone",
    MINIMAL: "Minimal",
    DAYLIGHT: "Daylight",
    WEATHER: "Weather",
    GURAPPS: "Gurapps",
    SECONDS: "Seconds",
    MOTION: "Motion",
    CONTRAST: "Contrast",
    WALLPAPER: "Wallpaper",
    ADD: "Add",
    STYLE: "Style",
    ADJUST: "Adjust",
    LANGPICK: "Language"
};

const LANG_JP = {
    GREETING: "ぐらするらいす読み込み成功",
    LICENCE: "ぐらするらいすはkirbIndustriesによって作られ、GNU General Public License, Version 2.0 (GPL-2.0)の下でライセンスされています。",
    WELCOME_MESSAGE: "こんにちは、ぐらすりすへようこそ！",
    PLACEHOLDER_MESSAGE: "メッセージを入力してください",
    SEND: "送信",
    VOICE: "音声",
    SEARCH_PLACEHOLDER: "検索",
    CONTROLS: "コントロール",
    SILENT: "サイレント",
    TONE: "トーン",
    MINIMAL: "最小",
    DAYLIGHT: "昼光",
    WEATHER: "天気",
    GURAPPS: "グラップス",
    SECONDS: "セコンド",
    MOTION: "モーション",
    CONTRAST: "コントラスト",
    WALLPAPER: "壁紙",
    ADD: "追加",
    STYLE: "スタイル",
    ADJUST: "調整",
    LANGPICK: "言語"
};
